#!/usr/bin/dash

password_store="$HOME/.password-store"
password_list=$(find "$password_store" -name '*.gpg' | sed "s/\.gpg$//" | sed "s|$password_store/||")

password=$(printf '%s' "$password_list" | dmenu "$@")
[ -n "$password" ] || exit

pass show "$password" | head -n 1 | xclip -selection clipboard
