#!/usr/bin/dash

dmenu="dmenu -l 5 -p password -nb "#000000" -nf "#ffffff" -sb "#0000ff" -sf "#ffffff""

password_store="$HOME/.password-store"
password_list=$(find -L "$password_store" -name '*.gpg' | sed "s/\.gpg$//" | sed "s|$password_store/||")

password=$(printf '%s' "$password_list" | $dmenu "$@")
[ -n "$password" ] || exit

pass show "$password" | sed -n '1p' | xclip -selection clipboard
